version: '3.4'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=yh
      - POSTGRES_DB=blogdb
    ports:
      - "5432:5432"

  api:
    image: ${DOCKER_REGISTRY-}blogapi
    build:
      context: .
      dockerfile: BlogAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Host=db;Database=blogdb;Username=yh;Password=root
      - JWT_KEY=ThisIsAVerySecretKeyForMyBloggingEngine2026
      - JWT_ISSUER=BlogAPI
      - JWT_AUDIENCE=BlogApp
    ports:
      - "5000:80"
    depends_on:
      - db
